### ISSUE TITLE
Port mapping

### ISSUE THREAD

**Issue by vivekshresta** [airavata-courses/IU-Witcher-2020#106]
How are you exposing the necessary ports for RabbitMQ since it cannot be done through Dockerfile?
![WhatsApp Image 2020-03-20 at 1 28 33 AM](https://user-images.githubusercontent.com/55638867/77170525-86a53e80-6a91-11ea-9253-abceac2fb213.jpeg)

**Comment by sanyam1997** [comment]
To handle port mapping, the first thing we did was initially try it with a docker-compose file. It was different from running it locally and because it wasn't hosted on a local machine that was already signed in and didn't require any credentials. The default credentials for signing into RabbitMq had to be added.

Besides, instead of the localhost, we had to add the IP at which RabbitMq was running. But since IP is bound to change we had to think of something which remained constant whenever we ran the file. And it was the image which was used as a replacement and it all worked. You can refer to the screenshot below for reference.

![Screenshot from 2020-03-20 16-44-04](https://user-images.githubusercontent.com/19321068/77204862-064eff80-6aca-11ea-9e86-e0e4ccedf398.png)

**Comment by vivekshresta** [comment]
Thanks for pointing out the code. Closing.
