### ISSUE TITLE
No output on UI during midnight

### ISSUE THREAD

**Issue by vivekshresta** [airavata-courses/IU-Witcher-2020#107]
When as a user I try to request for weather forecast data near midnight it doesn't show any output to the user, it just keeps on waiting for a request. Looks like a timezone issue to me.

**Comment by sanyam1997** [comment]
The data retrieval relies on the NEXRAD directory which has the date change at midnight. Although we have added the exception of taking in the second last element from the directory instead of the last one, to handle the error of incomplete file at that particular instant one is trying to access it. But for the date, such exception still is unable to handle that. So it's more like downtime for data-retrieval backend microservice. Hope this answers your query.

**Comment by vivekshresta** [comment]
Makes sense. Closing the issue.
