### ISSUE TITLE
Slave instance is not ready

### ISSUE THREAD

**Issue by ghost** [airavata-courses/IU-Witcher-2020#108]
Your slave is not ready in your cluster. Can you look into it?

![WhatsApp Image 2020-03-20 at 01 31 12](https://user-images.githubusercontent.com/5948157/77184528-57e59300-6aa6-11ea-9769-e64bfecc36ad.jpeg)

**Comment by sanyam1997** [comment]
After going through couple of trial and error and with discussions with the other users, I understood that the issue was with the security group. As can be seen in the screenshot below this is the security group rules which I had before.

**Comment by sanyam1997** [comment]
![SecurityGroup](https://user-images.githubusercontent.com/19321068/77203428-c0dd0300-6ac6-11ea-8d7f-2e528fd897c5.png)

**Comment by sanyam1997** [comment]
I have made the changes in the security group by adding the security rules to the cluster of ALL TCP and ALL UDP ports for connection and removing the 22 TCP port because ALL TCP ports are already included in that. You can try it now. I tried it on my end and all the nodes are in the ready state now.

**Comment by sanyam1997** [comment]
![Screenshot from 2020-03-20 16-24-28](https://user-images.githubusercontent.com/19321068/77203761-9ccdf180-6ac7-11ea-8d07-2c2d0b45e0f8.png)

**Comment by ghost** [comment]
Looks good. Thanks for quick update
