### ISSUE TITLE
Not many options to choose from among various radar ids available on github aws nexrad directory.

### ISSUE THREAD

**Issue by juhideshkar30** [airavata-courses/IU-Witcher-2020#48]

**Comment by sanyam1997** [comment]
Radar IDs are encoding on the basis of the nearest city are not available as such online. So finding the radar_id on the basis of a particular location the person is not available. So if we take radar id from the user it isn't the most user-friendly way of asking the user to tell him the weather because I as a user too couldn't spontaneously tell the system my radar id. So, for now, we have added a dropdown list with few options among which the user can be shown the prediction of the weather. We will work on it in the future to make to work upon in the future.
